---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker server image
      shell: docker pull kunalg3s/majorproject:server

    - name: pull docker front end image
      shell: docker pull kunalg3s/majorproject:client

    - name: Create back-end container

      docker_container:
        name: ts-backend

        image: kunalg3s/majorproject:server

        ports:
          - "6500:6500"

    - name: Create front-end container

      docker_container:
        name: ts-frontend

        image: kunalg3s/majorproject:client

        interactive: true

        ports:
          - "3000:3000"